### ISSUE TITLE
Update our plot

### ISSUE THREAD

**Issue by jules32** [jules32/collab-whoi#1]
We need to update our plot. @jafflerbach

**Comment by jules32** [comment]
More info: need to be commented

**Comment by jamiecmontgomery** [comment]
Ok I will comment it up!

**Comment by jamiecmontgomery** [comment]
Ok [here it is ](https://github.com/jules32/collab-whoi/blob/gh-pages/index.Rmd#L33)

**Comment by jules32** [comment]
Great, thanks!
